# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('E', 'Either')], default='E', max_length=1)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='BlockTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('total_rooms', models.PositiveSmallIntegerField(default=0)),
                ('total_singles', models.PositiveSmallIntegerField(default=0)),
                ('total_doubles', models.PositiveSmallIntegerField(default=0)),
                ('total_triples', models.PositiveSmallIntegerField(default=0)),
                ('total_quads', models.PositiveSmallIntegerField(default=0)),
                ('total_fivepulls', models.PositiveSmallIntegerField(default=0)),
                ('total_sixpulls', models.PositiveSmallIntegerField(default=0)),
                ('total_beds', models.PositiveSmallIntegerField(default=0)),
                ('closed_to', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], default='N', max_length=1)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_building', models.CharField(default='', max_length=100, verbose_name='Building name')),
                ('floor', models.PositiveSmallIntegerField()),
                ('display_name', models.CharField(default='', help_text='This will be the title of the image displayed to students. Ex. Floor 1 (West)', max_length=25)),
                ('image', models.ImageField(upload_to=staff.models.building_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lottery_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('E', 'Either')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('room_type', models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('T', 'Triple'), ('Q', 'Quad'), ('B', 'Block'), ('O', 'Other')], default='O', max_length=1)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('E', 'Either')], default='E', max_length=1)),
                ('pull', models.CharField(blank=True, default='', max_length=5)),
                ('total_beds', models.PositiveSmallIntegerField(default=0)),
                ('available_beds', models.PositiveSmallIntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('notes2', models.TextField(blank=True, default='')),
                ('apartment', models.ForeignKey(blank=True, help_text="If this room is part of an apartment, this is the apartment's number/name", null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Building')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='This is a name for this entry - it will not be displayed', max_length=50)),
                ('header_text', models.CharField(default='', help_text='This text will be displayed on the home page as a page title', max_length=50, verbose_name='Home page main text')),
                ('header_subtext', models.TextField(default='', help_text='This text will be displayed on the home page below the title in a smaller font', verbose_name='Home page lead text')),
                ('lottery_name', models.CharField(default='', help_text='This is the name of the current lottery', max_length=25)),
                ('contact', models.TextField(default='', help_text='This is a block of text explaining who to contact with any immediate questions')),
                ('edit_text', models.TextField(default='', help_text='This is a text description of the usage of editing options')),
                ('select_text', models.TextField(default='', help_text='This is a text description of the usage of selection options')),
                ('loto_num_text', models.TextField(default='', help_text='This is a text description of the usage of the lottery number input form', verbose_name='Number input text')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'updated',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puller_Number', models.PositiveSmallIntegerField()),
                ('Puller_Year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Puller_Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('E', 'Either')], default='E', max_length=1)),
                ('Pullee_Number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Pullee_Year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Pullee_Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('E', 'Either')], default='E', max_length=1)),
                ('Pullee_Room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pullee_Room', to='staff.Room')),
                ('Puller_Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Puller_Room', to='staff.Room')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='floor_plans',
            field=models.ManyToManyField(blank=True, to='staff.FloorPlan'),
        ),
        migrations.AddField(
            model_name='blocktransaction',
            name='residents',
            field=models.ManyToManyField(blank=True, to='staff.Resident'),
        ),
        migrations.AddField(
            model_name='blocktransaction',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Room'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Building'),
        ),
    ]
