# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_rooms', models.PositiveSmallIntegerField()),
                ('total_singles', models.PositiveSmallIntegerField()),
                ('total_doubles', models.PositiveSmallIntegerField()),
                ('total_triples', models.PositiveSmallIntegerField()),
                ('total_quads', models.PositiveSmallIntegerField()),
                ('total_beds', models.PositiveSmallIntegerField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('gender_blocked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField()),
                ('display_name', models.CharField(default='', help_text='This will be the title of the image displayed to students. Ex. Floor 1 (West)', max_length=25)),
                ('image', models.ImageField(upload_to=staff.models.building_directory_path)),
                ('related_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Building', verbose_name='building')),
            ],
        ),
        migrations.CreateModel(
            name='LotteryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('room_type', models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('T', 'Triple'), ('Q', 'Quad'), ('O', 'Other')], default='O', max_length=1)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], default='N', max_length=1)),
                ('pull', models.CharField(blank=True, default='', max_length=5)),
                ('total_beds', models.PositiveSmallIntegerField(default=0)),
                ('available_beds', models.PositiveSmallIntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('class_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lottery_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('notes2', models.TextField(blank=True, default='')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puller_Number', models.PositiveSmallIntegerField()),
                ('Puller_Year', models.PositiveSmallIntegerField()),
                ('Puller_Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], default='N', max_length=1)),
                ('Pullee_Number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Pullee_Year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Pullee_Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], default='N', max_length=1)),
                ('Pullee_Room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pullee_Room', to='staff.Room')),
                ('Puller_Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Puller_Room', to='staff.Room')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='floor_plans',
            field=models.ManyToManyField(blank=True, to='staff.FloorPlan'),
        ),
    ]
