# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('totalRooms', models.PositiveSmallIntegerField()),
                ('totalFloors', models.PositiveSmallIntegerField()),
                ('totalSingles', models.PositiveSmallIntegerField()),
                ('totalDoubles', models.PositiveSmallIntegerField()),
                ('totalTriples', models.PositiveSmallIntegerField()),
                ('totalQuads', models.PositiveSmallIntegerField()),
                ('totalBeds', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('genderBlocked', models.BooleanField()),
                ('closed', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
