# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='genderBlocked',
            new_name='gender_blocked',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='totalBeds',
            new_name='total_beds',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='totalDoubles',
            new_name='total_doubles',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='totalFloors',
            new_name='total_floors',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='totalQuads',
            new_name='total_quads',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='totalRooms',
            new_name='total_rooms',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='totalSingles',
            new_name='total_singles',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='totalTriples',
            new_name='total_triples',
        ),
    ]
