# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20160929_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('total_rooms', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], default='N', max_length=1)),
                ('available', models.BooleanField()),
                ('available_beds', models.PositiveSmallIntegerField()),
                ('total_beds', models.PositiveSmallIntegerField()),
                ('class_year', models.PositiveSmallIntegerField()),
                ('lottery_number', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Building'),
        ),
        migrations.AddField(
            model_name='room',
            name='pull',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Room'),
        ),
    ]
