# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20161003_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_rooms',
        ),
        migrations.AlterField(
            model_name='room',
            name='class_year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='lottery_number',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='pull',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Room'),
        ),
    ]
