# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20161003_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pull',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Room'),
        ),
    ]
