# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_lotterynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='notes2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('T', 'Triple'), ('Q', 'Quad'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_beds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='pull',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_beds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
