# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_lotterynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='notes2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('T', 'Triple'), ('Q', 'Quad'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
