# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20161012_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puller_Number', models.PositiveSmallIntegerField()),
                ('Puller_Year', models.PositiveSmallIntegerField()),
                ('Pullee_Number', models.PositiveSmallIntegerField()),
                ('Pullee_Year', models.PositiveSmallIntegerField()),
                ('Pullee_Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pullee_Room', to='staff.Room')),
                ('Puller_Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Puller_Room', to='staff.Room')),
            ],
        ),
    ]
