# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Pullee_Number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Pullee_Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pullee_Room', to='staff.Room'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Pullee_Year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
