# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20161012_0033'),
        ('staff', '0008_auto_20161012_0931'),
    ]

    operations = [
    ]
