# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_merge_20161014_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='notes2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_plans',
            field=models.ManyToManyField(to='staff.FloorPlan'),
        ),
    ]
