# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20161015_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='notes2',
            field=models.TextField(default=''),
        ),
    ]
