# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20161015_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='display_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
