# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_floorplan_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='building_name',
            field=models.CharField(help_text='This can be an abbreviation. Just for sorting purposes.', max_length=100),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='display_name',
            field=models.CharField(default='', help_text='This will be the title of the image displayed to students. Ex. Floor 1 (West)', max_length=25),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(help_text='The full size image of the floor plan', upload_to=''),
        ),
    ]
