# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_auto_20161015_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='building_name',
            field=models.CharField(default='', help_text='This will not be visible on the site - it can be an abbreviation', max_length=100),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(help_text='The full size image of the floor plan', upload_to='floorplans/'),
        ),
    ]
