# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_auto_20161015_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(upload_to=staff.models.building_directory_path),
        ),
    ]
