# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_auto_20161015_1717'),
        ('staff', '0010_auto_20161014_1627'),
    ]

    operations = [
    ]
