# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_merge_20161015_2251'),
        ('staff', '0022_auto_20161016_1300'),
    ]

    operations = [
    ]
