# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_merge_20161016_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Pullee_Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Puller_Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], default='N', max_length=1),
        ),
    ]
