# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20161017_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='building',
            name='location',
        ),
        migrations.RemoveField(
            model_name='building',
            name='total_floors',
        ),
        migrations.RemoveField(
            model_name='room',
            name='class_year',
        ),
        migrations.RemoveField(
            model_name='room',
            name='lottery_number',
        ),
        migrations.AddField(
            model_name='building',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='building',
            name='total_fivepulls',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='total_sixpulls',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='apartment_number',
            field=models.CharField(blank=True, default='', help_text="If this room is part of an apartment, this is the apartment's number/name", max_length=5),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_beds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_doubles',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_quads',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_singles',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_triples',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('E', 'Either')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('T', 'Triple'), ('Q', 'Quad'), ('B', 'Block'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Pullee_Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('E', 'Either')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Puller_Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('E', 'Either')], default='E', max_length=1),
        ),
    ]
